import 'package:meta/meta.dart';

/// Represents a snapshot of processed audio data for visualization.
///
/// This class contains normalized amplitude, peak frequency, and optional FFT
/// spectrum data generated by the audio controller.
@immutable
class AudioData {
  /// Creates an instance of [AudioData].
  const AudioData({
    required this.amplitude,
    required this.frequency,
    required this.timestamp,
    this.phase,
    this.spectrum,
  });

  /// The normalized amplitude of the audio signal (0.0 to 1.0).
  final double amplitude;

  /// The peak frequency of the audio signal in Hz.
  final double frequency;

  /// The point in time when this data was captured.
  final DateTime timestamp;

  /// The Phase of the audio signal in radians.
  final double? phase;

  /// The processed frequency spectrum data (FFT magnitudes).
  final List<double>? spectrum;

  /// Creates a copy of this [AudioData] with the given fields replaced.
  AudioData copyWith({
    final double? amplitude,
    final double? frequency,
    final DateTime? timestamp,
    final double? phase,
    final List<double>? spectrum,
  }) => AudioData(
    amplitude: amplitude ?? this.amplitude,
    frequency: frequency ?? this.frequency,
    timestamp: timestamp ?? this.timestamp,
    phase: phase ?? this.phase,
    spectrum: spectrum ?? this.spectrum,
  );

  @override
  bool operator ==(final Object other) {
    if (identical(this, other)) {
      return true;
    }
    return other is AudioData &&
        other.amplitude == amplitude &&
        other.frequency == frequency &&
        other.timestamp == timestamp &&
        other.phase == phase &&
        other.spectrum == spectrum;
  }

  @override
  int get hashCode =>
      Object.hash(amplitude, frequency, timestamp, phase, spectrum);

  @override
  String toString() =>
      'AudioData(amplitude: $amplitude, frequency: $frequency, '
      'timestamp: $timestamp, phase: $phase, spectrum: $spectrum)';
}
